### ISSUE TITLE
Add entity IDs in HTML

### ISSUE THREAD

**Issue by kenodressel** [BreakOutEvent/breakout-frontend#109]

**Comment by florianschmidt1994** [comment]
@Ardobras Why?

**Comment by Ardobras** [comment]
@florianschmidt1994 Mainly easier frontend access to various elements. Secondly about tracking which elments have been seen by user for automated bug / improvement reports.

**Comment by florianschmidt1994** [comment]
I will close this. Might be reopen / implemented with more detailed steps as new features / tracking use cases arise
