### ISSUE TITLE
Add sentence at the bottom of the team page.

### ISSUE THREAD

**Issue by kenodressel** [BreakOutEvent/breakout-frontend#131]
`Falls Du jetzt oder später mal bei BreakOut mitorganisieren möchtest, hier entlang: mitmachen@break-out.org`

`Sonstige andere Fragen an unser Team bzgl. Organisation, Finanzen oder Ähnliches, immer her damit: event@break-out.org`

**Comment by florianschmidt1994** [comment]
Currently not a requirement. Will reopen if wanted again
