### ISSUE TITLE
Add documentation on how to use the cms integration

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-frontend#177]
This is important for the future. We should document on how we integrated the contentful node.js library and how to use it in the future, if someone else should ever need to extend / fix stuff here

**Comment by florianschmidt1994** [comment]
@tomkellog @MkuuWaUjinga would you do me the honour? This is the last issue of this milestone 🎉

**Comment by tomkellog** [comment]
@florianschmidt1994 where would you like us to put the documentation?

**Comment by florianschmidt1994** [comment]
Would be perfekt if you could add a simple description to the [wiki](https://github.com/BreakOutEvent/breakout-frontend/wiki) of the breakout-frontend.

**Comment by tomkellog** [comment]
i gave it a shot; i you would like the docs to cover more (or less) information or if you prefer a description in greater detail, let me know!
