### ISSUE TITLE
Instagram Feed on landing page points to old account name

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-frontend#253]
Requested change: Change feed to new instagram account name (breakout_ev)

**Comment by ZackTaylor** [comment]
@florianschmidt1994 this will be my first open source contribution but id like to take a stab at this.

**Comment by ZackTaylor** [comment]
@florianschmidt1994 in what file would this change need to be made?

**Comment by florianschmidt1994** [comment]
Hey Zack,
nice to hear that you want to contribute to BreakOut, we really appreciate it! I'm currently at work, but I will dig out some information for you tonight. :)

**Comment by florianschmidt1994** [comment]
Unfortunately, this is not an issue. I reported this initially because the name of our instagram account changed, but the user_id is staying the same and the feed on the landingpage is still up to date. 

@ZackTaylor if you want have a look at other issues, we'd love to welcome you as a contributer here at BreakOut Development 👍
