### ISSUE TITLE
Correct social media links

### ISSUE THREAD

**Issue by dominikglandorf** [BreakOutEvent/breakout-frontend#255]
The Facebook, instagram and twitter links in the header and footer are broken. Correct links would be https://www.facebook.com/breakout.ev/
https://www.instagram.com/breakout_challenge/
Twitter?

**Comment by dominikglandorf** [comment]
Twitter: https://twitter.com/breakout_ev

**Comment by florianschmidt1994** [comment]
Closed with cbee2ad
