### ISSUE TITLE
Instagram feed on landing page is not working

### ISSUE THREAD

**Issue by MkuuWaUjinga** [BreakOutEvent/breakout-frontend#297]
The endpoint is deprecated and does not work any longer.
![image](https://user-images.githubusercontent.com/16869712/38336718-0cb0fe28-3863-11e8-97b4-88c3681bf7b9.png)

**Comment by dominikglandorf** [comment]
Konsole gibt aus:
Uncaught Error: Error from Instagram: This endpoint has been retired

**Comment by dominikglandorf** [comment]
Versuche einen neuen Access Token zu bekommen.

**Comment by dominikglandorf** [comment]
https://www.slickremix.com/instagram-api-change-on-april-4th-2018/
