### ISSUE TITLE
Implement new sponsor registration

### ISSUE THREAD

**Issue by dominikglandorf** [BreakOutEvent/breakout-frontend#299]
- [x] Change form fields
    - [x] Sponsor.handlebars 
    - [x] Profile.handlebars ab 195
- [x] Determine API endpoint and check fields
- [x] Adapt profile picture upload to cloudinary upload
- [x] Prefill form fiels
- [x] Change page title "Anmeldung zu BreakOut 2017 
- [x] Englische Übersetzungen

* Check Terms of Use for sponsorships: Up to date.
* What does "Hide profile in public" mean? Discuss with team finances!
* Select role after first selection still possible? Double roles possible.
* Gender policy? Not yet, coming soon!

**Comment by florianschmidt1994** [comment]
@dominikglandorf can we close this? I think?

**Comment by dominikglandorf** [comment]
Check :)
