### ISSUE TITLE
Find out how Deployment Process works

### ISSUE THREAD

**Issue by SimonK92** [BreakOutEvent/breakout-frontend#383]
Find out how Deployment Process works and comment it in readme.txt

**Comment by SimonK92** [comment]
Meeting on friday where Dominik attends who knows all about the deployment process hopefully.

**Comment by sibbl** [comment]
As written in our Slack channel, I got access yesterday, could successfully connect to the machine and was able to easily understand the current deployment process using the markdown documentation in the private production repo.

So please let me know if there's something more to know outside this Docker setup as I unfortunately cannot attend tomorrow's meeting.

Thinking long term, I'd suggest to move away from a VM setup as Azure offers resources which are easier to maintain and easier to integrate into a CI process using GitHub actions. Building Docker containers on Travis with an encrypted secrets archive and then having to manually run docker compose commands sounds like a common scenario which can and should be automated. But that'd be something for later once this year's event is over.

Understanding the load balancer and network setup might be helpful for this, but it's nothing urgent blocking us from short-term deployments and I'd suggest another issue to track this and collect details.
