### ISSUE TITLE
! Cookie Consent Banner

### ISSUE THREAD

**Issue by SimonK92** [BreakOutEvent/breakout-frontend#385]
A "we are using cookies" banner should be added to website. Search for legal rules and propose a possible design here first! (May be added to global template!)

Anscheinend gespeicherte Cookies: 
Google Analytics und Youtube

Banner-Text mindestens auf englisch.

TODO: Auf weitere Cookies checken

Diese beiden sind nicht essentiell, 
Anmeldung ist aber essentiell.

Cookie Consent Banner soll 2 Buttons beinhalten, "Alle annehmen" und "Nicht-Essentielle ablehnen"

**Comment by SimonK92** [comment]
Bisher wurde ein Instagram-Feed ebenfalls als Cookie verwendet.
Instagram-Kanal ist auf der Webseite verlinkt.

Instagram-Feed wird im Zuge des Tickets mit wieder zum Laufen gebracht.

**Comment by sibbl** [comment]
Instagram werde ich vorerst ausbauen, da es schon länger kaputt ist und Instagram auch die API umgebaut hat.

Die Bibliothek https://instafeedjs.com benötigt mittlerweile alle 60 Tage ein neues Token und die Library holt sich das über ein eigens für die Automatisierung dessen vorgesehenes Backend. Ist nach Rücksprache aktuell den Aufwand nicht wert (da eh schon länger kaputt), da die Nutzer dem Link zu Instagram folgen können.

D.h. ich kann den Rest zu Ende implementieren und mache mir über Instagram-Cookies vorerst keine weiteren Gedanken.

**Comment by SimonK92** [comment]
Aktuelle Bugs:
- Fehlende Translations für englisch.
- Cookie-Banner wird nur auf Homepage ("/") angezeigt.
