### ISSUE TITLE
Teilnehmer-Registrierung anpassen 

### ISSUE THREAD

**Issue by linatic7** [BreakOutEvent/breakout-frontend#387]
IST: wenn eine Person sich auf der Webseite registriert,  kann sie (sobald die Anmeldung geöffnet ist) auswählen, dass sie am BreakOut teilnehmen möchte. Dazu muss sie ein eigenes Teilnehmer-Profil mit folgenden Informationen erstellen: Name, T-Shirt-Größe, Handynummer, Notfallnummer, Startort. 
Diese Daten sollen im Nachhinein auch bearbeitbar sein. Zudem soll der Teilnehmer auswählen können, ob seine Beiträge und sein Name auf der Webseite in Klartext oder anonymisiert (nur der Vorname oder komplett anonym) erscheinen soll. 
https://break-out.org/settings/profile

**Comment by SimonK92** [comment]
![image](https://user-images.githubusercontent.com/79445517/161989263-25977ff9-c4f1-40fe-b7e4-54454d83303c.png)

**Comment by JosiBreakOut** [comment]
![Teilnehmer](https://user-images.githubusercontent.com/102240990/161994755-8c0f6828-24ea-4d3c-bc09-39492b303743.PNG)

Teilnehmerregistrierung klappt aber bitte die Darstellung der Kästchen anpassen, damit man diese anklicken kann.
Mobile und auf der englischen Seite  geht es.

**Comment by JosiBreakOut** [comment]
Kann man es möglich machen in Profil/Account ein gesamtes Teamprofil zu löschen? 
Gerne an dem Test Profil was ich erstellt habe, denn das soll weder gelöscht werden --> Team 644

Theoretisch optional, Funktion vielleicht erst nach 14.4. implementieren bei fehlender Zeit.
Mindestens Testprofil löschen!

**Comment by SimonK92** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/79445517/162612304-2272cf3d-5765-48f7-8782-ef9d7638160a.png">

**Comment by SimonK92** [comment]
@JosiBreakOut Bei mir geht die Darstellung. Magst du mir deinen Testfall mal schicken, also welches Setup? Können uns das gerne auch zusammen ansehen.

**Comment by JosiBreakOut** [comment]
@SimonAbat was meinst du mit Setup? Meine Darstellung auf dem Laptop in Chrome passt leider nicht und sieht so aus wie auf dem Screenshot. Ansonsten kann ich aber gern meinen Bildschirm teilen.

**Comment by SimonK92** [comment]
wäre super! @JosiBreakOut 
heute noch oder morgen? :)

**Comment by SimonK92** [comment]
IST: Shipping-Date: 15.6.2021 
SOLL: 20.6.2022

**Comment by SimonK92** [comment]
Tshirtgröße muss direkt geladen werden.
Checkboxen müssen wieder auf required gesetzt werden.
