### ISSUE TITLE
Team-Partner einladen und Team beitreten können

### ISSUE THREAD

**Issue by linatic7** [BreakOutEvent/breakout-frontend#388]
Wenn ein Teilnehmer ein Teamprofil erstellt, dann soll er die E-Mail-Adresse seines Teampartners angeben. Diese sollte später im Team-Profil auftauchen und bearbeitbar sein. https://break-out.org/settings/profile
 Daraufhin wird eine Einladungs-Mail an den Teampartner versendet. In dieser steht ein Link der für den Beitritt in dieses Team gültig ist.  Hat der Teampartner sich bereits auf der Webseite als Teilnehmer registriert, kann er über einen Button “Team beitreten” über eine Suchmaske mit Teamvorschlägen in einem Dropdown sein Team für 2022 auswählen (wenn er eine Einladung erhalten hat).  Anschließend haben beide Team-Mitglieder Zugang auf das Team-Profil und sind als ein Team gematcht. https://break-out.org/team/515

(1 Tag)

Ist:
Die E-Mail des Teampartners wird abgefragt und eine Mail wird versandt.

Soll:
falls die E-Mail falsch war, sollte man in den Teamdaten die E-Mails einsehen und bearbeiten können und eine neue bestätigunsmail mit der geänderten Adresse verschicken können.

Woher kommen die automatisierten Mails nach Teamerstellung? Wir müssen noch Spendenpartner auf Zeltschule e.V. anpassen und das Überweisungsdatum auf den 1.6.

Shipping-Date:
IST: 15.6.2021
SOLL: 20.6.2022

**Comment by SimonK92** [comment]
Automatisierte Mails:
Anpassung des Spendenpartners und des Datums.

**Comment by SimonK92** [comment]
Außerdem: Es soll klar sein, welche Emailadresse als Mit-Teilnehmer angegeben wurde, bis der Registrierungsprozess vom eingeladenen Partner abgeschlossen ist.

**Comment by SimonK92** [comment]
Shipping-Date:
IST: 15.6.2021
SOLL: 20.6.2022

**Comment by linatic7** [comment]
In der Mail:  Ein letzter Schritt zur Anmeldung, die verschickt wird,  sobald das Team vollständig ist, sind die falschen Bankdaten hinterlegt. Ebenfalls in der Meldung im Teamprofil, hier muss zusätzlich das Datum auf 1.6. statt 31.5. geänder werden (passt in er Mail bereits)
IST: 
Kontoinhaber: BreakOut e.V.
IBAN: DE85 7002 2200 0020 2418 37
BIC: FDDODEMMXXX

SOLL: 
Kontoinhaber: BreakOut e.V.
IBAN: DE78 1001 7997 1735 6121 29
BIC: HOLVDEB1
Kreditinstitut: Holvi Payment Services Oy
