### ISSUE TITLE
Passwort-vergessen Button

### ISSUE THREAD

**Issue by linatic7** [BreakOutEvent/breakout-frontend#389]
Auf der Loginseite (https://break-out.org/login) soll ein Button “Passwort vergessen” angezeigt werden. Wird dieser Button bestätigt, kann der Nutzer (Teilnehmer, Sponsor, Zuschauer) nach Eingabe seiner E-Mail-Adresse sein Passwort zurücksetzen. (wie das gelöst wird, ist egal).

**Comment by sibbl** [comment]
@linatic7 @JosiBreakOut was genau reicht denn an dem bestehenden "Passwort vergessen"-Link nicht aus, dass es dieses Ticket hier gibt?

<img width="177" alt="image" src="https://user-images.githubusercontent.com/866535/161986063-29631b09-0c76-49c8-929b-6a41ead870a4.png">

**Comment by JosiBreakOut** [comment]
@sibbl ich dachte ehrlich gesagt, dass es mit dem Button Probleme gab. bei mir hat es jetzt jedoch funktioniert. 
Vielleicht kann ja @linatic7 nochmal testen und wir fragen nochmal Kathrin was bei ihr nicht funktioniert hatte. Wenn dabei kein Fehler rauskommt, dann darf das Ticket gern auf Done.
