### ISSUE TITLE
Passwort / E-Mail-Adresse im Profil ändern

### ISSUE THREAD

**Issue by linatic7** [BreakOutEvent/breakout-frontend#390]
Auf der Profilseite des Benutzers (Teilnehmer, Sponsor, Zuschauer) soll die eigene Anmelde-E-Mail-Adresse geändert und das Passwort geändert werden können. (Umsetzung egal) https://break-out.org/settings/profile

(2 Tage) Frontend+Backend

**Comment by SimonK92** [comment]
Problem:
Wenn wir nur 1 Emailfeld nutzen, funktioniert die Validierung nicht mehr wie gewollt.
Wir brauchen ein zusätzliches Feld in der Datenbank, um die beiden Werte E-Mail-Alt und E-Mail-Neu zu speichern.
Außerdem muss das Frontend angepasst werden, dass der User beide E-Mailadressen sehen kann.

TODO:
- Zweites Feld im Frontend. Unterscheidung E-Mail-Alt und E-Mail-Neu.
 - Sichtbar nur, wenn wir gerade im Verifizierungsprozess sind, bedeutet: E-Mail-Alt !== E-Mail-Neu
- Anpassung der DB-Struktur und aller jeweiligen Typen/ Interfaces
- Implementierung Logik, die bei neuer E-Mailadresse den Verifizerungsprozess neu startet
- Unit Tests

**Comment by SimonK92** [comment]
E-Mailfelder gehen.
Passwort ist noch zu tun.
Sebastian supportet Malvina bei Backend-Thematiken.

**Comment by JosiBreakOut** [comment]
Ich kann meine neue E-Mail-Adresse nicht bestätigen.
![Screenshot_20220412-145719](https://user-images.githubusercontent.com/102240990/162967948-ccb50408-66e0-48db-9299-b5eb1017eb77.png)
