### ISSUE TITLE
Countdown auf Live-Blog updaten

### ISSUE THREAD

**Issue by linatic7** [BreakOutEvent/breakout-frontend#394]
Countdown bis zum 24.6.2021 um 9 Uhr einstellen
Gesamtspenden und Gesamtkilometer auf Null setzen
https://break-out.org/live

(0,5 Tage) Frontend

**Comment by SimonK92** [comment]
Erster Eindruck:
Sollte man im Admin-Panel ändern können bzw resetten können.

Malvina und Josi sehen sich das zusammen an, fallst nicht im Admin-Tool änderbar -> Codechange.

**Comment by SimonK92** [comment]
Wenn über das Admin-Panel ein neues Event erstellt wurde, wird der Countdown automatisch resettet.
Josi testet das nochmal und schiebt es dann auf Done.
