### ISSUE TITLE
[Fachlich] DSGVO | Teilnehmer-/ Sponsoren - und andere personenbezogene Daten sollen und müssen jederzeit auf Anfrage vollständig abrufbar sein

### ISSUE THREAD

**Issue by SimonK92** [BreakOutEvent/breakout-frontend#397]

**Comment by sibbl** [comment]
Auf der Datenschutz-Unterseite ist eine Kontakt-E-Mail-Adresse genannt. Bei entsprechenden Anfragen an diese können wir über Endpunkte der Anwendung bzw. Datenexporte direkt aus der Datenbank Auskunft geben. Weitere eventuelle Weitergaben von Daten außerhalb der Softwareplatform sollten anderweitig beantwortet werden können, sofern dies überhaupt zukünftig geschehen und dadurch notwendig werden sollte.

**Comment by SimonK92** [comment]
Dementsprechende Anfragen werden gelesen.
Bei technischen Fragen wird Sebastian kontaktiert.
