### ISSUE TITLE
Event anlegen

### ISSUE THREAD

**Issue by JosiBreakOut** [BreakOutEvent/breakout-frontend#407]
Event anlegen, bei dem sich die Teilnehmer und Sponsoren dann registrieren können. 
Name: BreakOut 2022 Anywhere

Lena und Josi können über das Admin Tool auf der Website ein neues Event erstellen, aber man kann sich dafür dann trotzdem nicht über den Registrations-Button anmelden.
![Admin Tool BreakOut](https://user-images.githubusercontent.com/102240990/160841556-77ebf76f-8723-4e00-a2b4-6cf5b1ff4757.PNG)
 
(1,5 Tage)

**Comment by SimonK92** [comment]
Malvina hat lokal als Admin im Admin-Tool das Event angelegt.
Bei Josi hats auch geklappt.

Josi testet nochmal auf PROD ob alles geht wie gewünscht und schiebt es dann auf Done.
