### ISSUE TITLE
Startort angeben

### ISSUE THREAD

**Issue by linatic7** [BreakOutEvent/breakout-frontend#425]
create-join-team
Text im Adressfeld ändern

Starterkit:
If you want to start in München, please write us: "Start and Pick up at the starting location" 
If you want to start from home, please tell us the address (name, street + nr., PLZ + city) where your starterkit will be sent to (shipping date approx. 20.06.22, shipping only available in Germany)*

Starterkit:
Wenn du am Startort in München startest, schreibe uns dies bitte: "Start und Abholung am Startort"
Falls du von zuhause starten möchtest, nenn uns bitte die Anschrift (inkl. Name, Straße + Hausnr, PLZ + Ort) an die euer Starterkit verschickt werden soll (Versanddatum ca. 20.06.22, Versand nur nach Deutschland möglich)*

**Comment by sibbl** [comment]
@linatic7 Zeilenumbrüche kann ich leider an der Stelle nicht so leicht einfügen. Aber dürfte auch so gehen, oder was sagst du?

<img width="621" alt="image" src="https://user-images.githubusercontent.com/866535/169824170-6ed39225-8c7b-4975-9834-a087fbdeb7a4.png">

**Comment by sibbl** [comment]
Update: ich ändere noch die Label-Schriftfarbe von `gray-light` zu `gray-dark`:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/866535/169826232-28885b95-0a99-4356-9913-f1f2b7954d14.png">
