### ISSUE TITLE
Add menu rendering

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/breakout-frontend#47]

**Comment by florianschmidt1994** [comment]
@Ardobras What does this mean? Can it be closed?

**Comment by Ardobras** [comment]
@florianschmidt1994 it was basically about making the menu dynamic, to reflect login/logout state and other context sensitive changes.

**Comment by florianschmidt1994** [comment]
Closed with d5de9be9f28871505e616434e5be30d08e225b03
