### ISSUE TITLE
Error when trying to become a participant without providing an image

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-frontend#67]
I registered successfully as user, and when trying to become a participant without adding a photo, I had the following error:

```
TypeError: data.delete is not a function. (In 'data.delete('profilePic')', 'data.delete' is undefined')
(anonymous function) - registration.js:138
dispatch - bundle.js:1067:204
handle - bundle.js:1043:97
```

Browser: Safari 9.1
OS: OS X El Capitan 10.11.4

**Comment by thepiwo** [comment]
workaroung provided, has to be solved more elegantly

https://github.com/BreakOutEvent/breakout-frontend/commit/957fdc3b3b6a8ccfe39d357f6607580797e55f8d

**Comment by florianschmidt1994** [comment]
I will close this, as 
1. A workaround was provided 
2. Uploading a profile picture is not a part of the registration process anymore
